In [ ]:
import pandas as pd
df = pd.read_parquet("data.parquet")
display(df.head(100))

,Brand,Model,Power,Date,Mileage,Transmission,Fuel,Drive Type,Price
0,Skoda,Octavia,81,1/2016,,Automatic,Petrol,,11199
1,Fiat,Ducato,103,7/2021,90000km,Manual,Diesel,,22749
2,Mercedes-Benz,Vito,120,3/2021,170000km,Automatic,Diesel,,19299
3,Chevrolet,Spark,50,2/2012,161000km,Manual,Petrol,,3399
4,Nissan,Micra,59,6/2014,162000km,Manual,Petrol,,2599
...,...,...,...,...,...,...,...,...,...
95,Fiat,Talento,107,9/2020,114159km,Manual,Diesel,,10199
96,Mazda,MX-30,105,11/2020,105261km,Automatic,Hybrid,,17449
97,Nissan,Leaf,110,9/2023,1697km,Automatic,Electric,,18449
98,Isuzu,D-Max,120,6/2023,20000km,Automatic,Diesel,4x4,38249
99,Mercedes-Benz,Vito,120,6/2021,99218km,Automatic,Diesel,,24599

In [3]:
df.shape

(1078436, 9)